### ISSUE TITLE
你好，装了字体后还是显示没有鲁迅字体，编译方式是xelatex吗？

### ISSUE THREAD

**Issue by jlduu** [cs-qyzhang/LaTeX-Diary#1]

**Comment by cs-qyzhang** [comment]
你好，很高兴你能够使用这个模板。请问你所使用的系统是否是 Windows？我记得在 Windows 下 XeLaTeX 识别字体会有些问题，似乎不能够直接使用字体名。但好像可以使用字体的文件名，或者使用 Path 可选参数来指定字体的路径。另外还有一种方式是把 Windows 的字体目录加入到 fontconfig 的查找路径中，比如在 `C:\texlive\2021\texmf-var\fonts\conf\fonts.conf` 文件中加入以下一行：

```
<dir>C:\Users\yourname\AppData\Local\Microsoft\Windows\Fonts</dir>
```

详见 <https://tex.stackexchange.com/questions/45478/how-to-make-xelatex-recognize-linked-fonts-with-windows>。

总而言之，在 Windows 下 XeLaTeX 识别用户安装的字体有些麻烦，你需要参考 fontconfig 查找字体的方法来做出相应的改变。你也可以尝试使用 LuaLaTeX 进行编译（我不确定是否可以直接编译），LuaLaTeX 对字体的查找会更先进些，不过 LuaLaTeX 运行速度有点慢。

**Comment by jlduu** [comment]
> 你好，很高兴你能够使用这个模板。请问你所使用的系统是否是 Windows？我记得在 Windows 下 XeLaTeX 识别字体会有些问题，似乎不能够直接使用字体名。但好像可以使用字体的文件名，或者使用 Path 可选参数来指定字体的路径。另外还有一种方式是把 Windows 的字体目录加入到 fontconfig 的查找路径中，比如在 `C:\texlive\2021\texmf-var\fonts\conf\fonts.conf` 文件中加入以下一行：
> 
> ```
> <dir>C:\Users\yourname\AppData\Local\Microsoft\Windows\Fonts</dir>
> ```
> 
> 详见 https://tex.stackexchange.com/questions/45478/how-to-make-xelatex-recognize-linked-fonts-with-windows。
> 
> 总而言之，在 Windows 下 XeLaTeX 识别用户安装的字体有些麻烦，你需要参考 fontconfig 查找字体的方法来做出相应的改变。你也可以尝试使用 LuaLaTeX 进行编译（我不确定是否可以直接编译），LuaLaTeX 对字体的查找会更先进些，不过 LuaLaTeX 运行速度有点慢。

**Comment by jlduu** [comment]
> 你好，很高兴你能够使用这个模板。请问你所使用的系统是否是 Windows？我记得在 Windows 下 XeLaTeX 识别字体会有些问题，似乎不能够直接使用字体名。但好像可以使用字体的文件名，或者使用 Path 可选参数来指定字体的路径。另外还有一种方式是把 Windows 的字体目录加入到 fontconfig 的查找路径中，比如在 `C:\texlive\2021\texmf-var\fonts\conf\fonts.conf` 文件中加入以下一行：
> 
> ```
> <dir>C:\Users\yourname\AppData\Local\Microsoft\Windows\Fonts</dir>
> ```
> 
> 详见 https://tex.stackexchange.com/questions/45478/how-to-make-xelatex-recognize-linked-fonts-with-windows。
> 
> 总而言之，在 Windows 下 XeLaTeX 识别用户安装的字体有些麻烦，你需要参考 fontconfig 查找字体的方法来做出相应的改变。你也可以尝试使用 LuaLaTeX 进行编译（我不确定是否可以直接编译），LuaLaTeX 对字体的查找会更先进些，不过 LuaLaTeX 运行速度有点慢。

非常感谢！“把 Windows 的字体目录加入到 fontconfig 的查找路径中”非常有效，然后调用字体时使用字体的文件名加上ttf后缀就可以。
